name: tko_trial

profile: tko_trial

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  tko_trial: # Change this to your actual project name
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts
